### Object Detection using OpenCV-Python 

In [9]:
import cv2
import numpy as np

In [10]:
img = cv2.imread('img2.jpg')

In [11]:
classNames = []
classFile = 'coco.names'
with open(classFile,'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

In [12]:
print(classNames)

['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'street sign', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'hat', 'backpack', 'umbrella', 'shoe', 'eye glasses', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'plate', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'mirror', 'dining table', 'window', 'desk', 'toilet', 'door', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'blender', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush', 'hair brush']


In [13]:
# loading our weights and config files path into variables
configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

In [14]:
# setting up our model with DNN module
net = cv2.dnn_DetectionModel(weightsPath,configPath) #loading file paths
net.setInputSize(320,320) #changing the size of the image frame
net.setInputScale(1.0/ 127.5) # scaling by a factor of 1/127.5 = 0.00784
net.setInputMean((127.5, 127.5, 127.5)) # mean subtraction
net.setInputSwapRB(True)

<dnn_Model 000001B529EB1EB0>

In [15]:
classIds, confs, bbox = net.detect(img, confThreshold=0.5) # Threshold set to 50%
print(classIds, confs, bbox)

[[3]
 [1]
 [1]
 [3]
 [3]
 [1]
 [1]
 [1]
 [1]
 [8]] [[0.70080125]
 [0.68650836]
 [0.67390025]
 [0.6460168 ]
 [0.6257855 ]
 [0.6153716 ]
 [0.60868055]
 [0.60698396]
 [0.57177645]
 [0.51644576]] [[ 61  58  53  42]
 [274  62  11  23]
 [289  63  10  22]
 [125  60  20  16]
 [110  59  24  18]
 [260  60  12  24]
 [191  51  22  58]
 [214  44  34  70]
 [153  51  30  63]
 [ 61  57  54  42]]


In [16]:
# In this we iterate through the classID, confidence and bounding box values to draw a rectangle box
# on the screen and insert a text pertaining to the classID of the object detected

if len(classIds) != 0:
    for classId, confidence, box in zip(classIds.flatten(),confs.flatten(),bbox):
        cv2.rectangle(img, box, color=(0,255,0), thickness=2)
        # inserts a bounding box
        
        cv2.putText(img, classNames[classId-1].upper(),(box[0]+10,box[1]+30),
        cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        
        cv2.putText(img,str(round(confidence*100,2)),(box[0]+200,box[1]+30),
        cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        #inserts classID and cofidence % 
        

In [17]:
cv2.imshow('output', img)
cv2.waitKey(0)

-1